// Sin `'use client'` a proposito: la frontera se declara en cada componente, y asi `page.tsx`
// sigue siendo Server Component aunque importe desde aqui.
export {
  PACKING_ORDER_BACK_LINK_TESTID,
  PACKING_ORDER_FINISH_BUTTON_TESTID,
  PACKING_ORDER_FINISH_ERROR_TESTID,
  PACKING_ORDER_FINISH_FORM_TESTID,
  PACKING_ORDER_ID_FIELD,
  PACKING_ORDER_MISSING_DISTRIBUTION_TESTID,
  PACKING_ORDER_NUMBER_TESTID,
  PACKING_ORDER_PACKAGES_TESTID,
  PACKING_ORDER_PACKER_TESTID,
  PACKING_ORDER_PRESENTATION_LINE_TESTID,
  PACKING_ORDER_PRESENTATION_TESTID,
  PACKING_ORDER_QUANTITY_TESTID,
  PACKING_ORDER_RECIPE_TESTID,
  PACKING_ORDER_SCREEN_TESTID,
  PACKING_ORDER_START_BUTTON_TESTID,
  PACKING_ORDER_START_ERROR_TESTID,
  PACKING_ORDER_START_FORM_TESTID,
  PACKING_ORDER_STATUS_TESTID,
  PackingOrderScreen,
  type PackingOrderScreenProps,
} from './packing-order-screen';
